name: GitHub-Profile-3D-Contribution

on:
  schedule: # every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: plpatil1  # Your GitHub ID
          MAX_REPOS: 250
      - name: Commit & Push
        run: |
          git config user.name plpatil1  # Your GitHub ID
          git config user.email plpatil1151@gmail.com  # Your email
          git add -A .
          git commit -m "GitHub 3D Profile"
          git push
